// <auto-generated />
using Inventory_M.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryM.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20230503131326_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inventory_M.Models.users_management.UserToRole", b =>
            {
                b.Property<int>("UserToRoleId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserToRoleId"));

                b.Property<int>("RoleId")
                    .HasColumnType("int");

                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.HasKey("UserToRoleId");

                b.HasIndex("RoleId");

                b.HasIndex("UserId");

                b.ToTable("UserToRole");
            });

            modelBuilder.Entity("Inventory_M.Models.users_management.role", b =>
            {
                b.Property<int>("RoleId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                b.Property<string>("rolename")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("RoleId");

                b.ToTable("Roles");
            });

            modelBuilder.Entity("Inventory_M.Models.users_management.user", b =>
            {
                b.Property<int>("UserId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Lname")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PassWord")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("status")
                    .HasColumnType("bit");

                b.HasKey("UserId");

                b.ToTable("Users");
            });

            modelBuilder.Entity("Inventory_M.Models.users_management.UserToRole", b =>
            {
                b.HasOne("Inventory_M.Models.users_management.role", "Role")
                    .WithMany("UsersToRoles")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Inventory_M.Models.users_management.user", "User")
                    .WithMany("UsersToRoles")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Role");

                b.Navigation("User");
            });

            modelBuilder.Entity("Inventory_M.Models.users_management.role", b =>
            {
                b.Navigation("UsersToRoles");
            });

            modelBuilder.Entity("Inventory_M.Models.users_management.user", b =>
            {
                b.Navigation("UsersToRoles");
            });
#pragma warning restore 612, 618
        }
    }
}
